sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '0.12'
  - v4
  - stable
after_success:
  - travis-after-all && npm run semantic-release
env:
  global:
    - secure: d7yXMRidif8pecAGnDL91IwkWr67n4Cxt7xJZttH8Rnj8lQOF3T6Oh5IEfrO4tCWByZclME28xm3gU33QMMEItiX+mCLEv9nXWSWseSlKkTgnupBp9ZbLIIeZrUlDqIOlhNQ7gK7Op58uqmNcdXh+5AIcLPcOqLiIe1DtS4Ai66g9dvQcuWW2MKcv9IkpWmW0Xqb7WGo3GyVucjxqnU5Wniyukkmf95PPtUJpConrvxRATWnfYHCELHuzFJYXm2lJj9Syx3DzhbzNHFDYM1kyQafSkcQn+c8LbOQFYhdjZ9y3BlNZ7vXGTK/lsBZR59fpK9OPPyehLmgQ23Oy/iju6VwUySgZzSFue7e+ZgnDX9f2xEe8n0fBdZWClmbPyl0Yebi4/pWPc1LcDnJDQZ/F4b5uCMopig7bmcKE3axyC+qsrx/hO2vNmN+KNRPleAFfYrQGWW5hBTNyA1LuE38za4NoX0Pm3cAWJXX9gMwmiU9Vj0hTHLkyl3nWUo7Xv6b7FJ87WuAownahCeUE/PPgS0lu69Rb43kbPNDsNz0MDJOOQSONn2HkoVag3nY+zKkIs+e6/c7eE+ipuvRp7ZmhgpMsrO85oA3xqCgIBaWXH9mGEriK/ovH18rP69cSyiV+/Ez9M/eVpoSMM8usHqj6iJdsP1IwLDn+SlD54Lvy28=
    - secure: KB9MEQQXAegTmoZhtpkMFqAXYFyyV+ei7cS6axLgIf1Btwla3EMtV62Q2vbPhkMfpexm9FDfxVE03SUEhAXH2oL27DtvtrR+mBW3D10M/mgC+ZxR9cglfQM0Hs4nzn0edNP1ASyWd1a+aQ8TEgCGMROuRfZklx95Vjn00TjLb/7X8EqjJSY6DLHLUVUfJT15GMjlU9IESRXT/0xbv745XT8lhYtQON/iSb7wC5Twhr3YkbJNRWqu3HTh6mHzpWCMsJWaZCV4BVDdJS4ZnXI80b7AEI3wuqDqz6gPN4zSDn0dO8m8Z1aOLBTouO5cFcdUmril1r5wK7MpNgRUUWId1w9Jk24ENzdP2GlSPqjBsRrAV7SgxNJ4pm1tBiuoiYpUfOSb7a8MR5M8Zqu+pXUIY/rvBFQvU/fSAC2QdzxuSgKlzBSumUBQ19eKcBOOYixW/RUOT3FGhpYauWZvAj44PysZ8bjA2CGgOOcq9v2eF4nidLFvlUQzocjgqjuT5JHr7NCoX8zlKxBGZrdXE0D+PJqC4iiAnrlaKKFoLnmXVbN2sidy37IW5XIIh5huH5JkkqCibikC+DPC+nlQywenNkfKM+I03MFL8SSOn+C53+YafiZjF/cZtwyyo5odL429jCSEneDnMdlD+7xqLsaiBdV0ssqdjLRE7r2h17VJ7DI=
